import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import UserContextProvider from "./UserContextProvider";
import { ActiveTimeProvider } from "./ActiveTimeContext"; // adjust path as needed

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#121212] antialiased h-screen overflow-hidden no-scrollbar`}
        style={{
          userSelect: "none",
          WebkitUserSelect: "none",
          MozUserSelect: "none",
        }}
      >
        <UserContextProvider>
          <ActiveTimeProvider>{children}</ActiveTimeProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
